services:
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: tei-publisher-app
        APP_TAG_OR_BRANCH: v8.0.0
        APP_REPO: https://github.com/eeditiones/tei-publisher-app.git
        NER_ENDPOINT: http://ner:8001
        CONTEXT_PATH: "" # TEI Publisher will be mapped to the root of the website
        PROXY_CACHING: false
    # comment in to automatically restart:
    # restart: always
    volumes:
      # database files will be stored in a volume to avoid data loss
      # when the service is updated
      - /exist/data
      # uncomment to map eXist-db backups to local directory
      # - ./backup:/exist/backup
    depends_on:
      - ner
  ner:
    # image will be pulled from github
    image: ghcr.io/eeditiones/tei-publisher-ner/teipublisher-ner:master
    # enable if you want to build from source:
    # build:
    #   context: https://github.com/eeditiones/tei-publisher-ner.git#master
    #   dockerfile: Dockerfile
    # comment in to automatically restart:
    # restart: always
  frontend:
    image: nginx:alpine
    environment:
      - ROOT_PATH=/exist/apps/tei-publisher
      - SERVER_NAME=example.com
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./nginx/templates:/etc/nginx/templates/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - publisher
    # comment in to automatically restart:
    # restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw